# Generated by Django 3.2.8 on 2021-12-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='Middle_Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.TextField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Home_Address',
            field=models.TextField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_Number',
            field=models.TextField(default='default', max_length=12),
        ),
    ]
