# Generated by Django 3.2.8 on 2021-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.TextField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default='default', max_length=12),
        ),
    ]
