# Generated by Django 3.2.8 on 2021-12-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211205_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
    ]
