# Generated by Django 3.2.8 on 2021-12-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouncer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dimensions', models.TextField(max_length=20)),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
