# Generated by Django 3.2.8 on 2021-12-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouncers', '0002_bouncer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouncer',
            old_name='user',
            new_name='User',
        ),
    ]
