# Generated by Django 3.2.8 on 2021-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncers', '0004_rename_name_bouncer_itemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouncer',
            name='ItemName',
        ),
        migrations.AddField(
            model_name='bouncer',
            name='Item_Name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
