# Generated by Django 3.2.8 on 2021-12-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouncers', '0005_auto_20211203_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouncer',
            old_name='Item_Name',
            new_name='Items',
        ),
    ]
